Year_list = (1999,2003,2011,2017)
Month_list = ("Mar","Jun","Jan","Dec")
Day_list = (11,21,13,5)
result=zip()
result_list=list(result)
print(result_list)
result=zip(Year_list,Month_list,Day_list)
result_set=set(result)
print(result_set)
